### ISSUE TITLE
New code players cannot create new characters

### ISSUE THREAD

**Issue by sht547** [AlanMorel/MapleServer2#706]
[06:47:54] [DBG] LoginHandler: Logging in with account ID: 1
[06:47:54] [DBG] LoginHandler: Initializing login with account id: 1
[06:47:54] [DBG] Session: SEND (LoginResult - 0x000A): 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 9A 33 BA 62 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
[06:47:54] [DBG] Session: SEND (UGC - 0x006D): 11 22 00 68 00 74 00 74 00 70 00 3A 00 2F 00 2F 00 31 00 32 00 37 00 2E 00 30 00 2E 00 30 00 2E 00 31 00 3A 00 33 00 30 00 30 00 30 00 2F 00 77 00 73 00 2E 00 61 00 73 00 6D 00 78 00 3F 00 77 00 73 00 64 00 6C 00 15 00 68 00 74 00 74 00 70 00 3A 00 2F 00 2F 00 31 00 32 00 37 00 2E 00 30 00 2E 00 30 00 2E 00 31 00 3A 00 33 00 30 00 30 00 30 00 02 00 6E 00 61 00 02
[06:47:54] [DBG] Session: SEND (CharMaxCount - 0x00BA): 07 00 00 00 0B 00 00 00
[06:48:06] [DBG] Session: RECV (CharManagement - 0x0009): 01 01 5A 00 05 00 73 00 73 00 73 00 73 00 73 00 6F A4 D9 FF 6F A4 D9 FF 1B 01 07 0C A4 9B 00 02 00 48 00 52 00 4D 89 F9 FF 34 6B E2 FF 14 3C 93 FF 01 00 00 00 02 00 00 00 9A 99 99 3E 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 3F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 74 2A 9D 00 02 00 46 00 41 00 34 48 7F FF 4A 54 66 FF 02 0B 19 FF 08 00 00 00 03 00 00 00 11 B1 9E 00 02 00 46 00 44 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF 00 00 00 00 F6 7F A6 3E 2E 01 78 3C 5C 8F 42 3E 00 00 00 00 32 F6 AD 00 02 00 43 00 4C 00 A5 51 85 FF DB 85 4C FF 47 2A 35 FF 06 00 00 00 0A 00 00 00 75 7C AF 00 02 00 50 00 41 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF 00 00 00 00 7F 8A B2 00 02 00 53 00 48 00 A5 51 85 FF DB 85 4C FF 47 2A 35 FF 06 00 00 00 0A 00 00 00 A1 37 A0 00 02 00 45 00 52 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF 00 00 00 00 03 00 00 00
[06:48:07] [FTL] Session: Exception in recv PipeScheduler: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Types.Player..ctor(Account account, String name, Gender gender, Job job, SkinColor skinColor) in E:\MapleServer2\MapleServer2\Types\Player.cs:line 197
   at MapleServer2.PacketHandlers.Login.CharacterManagementHandler.HandleCreate(LoginSession session, PacketReader packet) in E:\MapleServer2\MapleServer2\PacketHandlers\Login\CharacterManagementHandler.cs:line 158
   at MapleServer2.PacketHandlers.Login.CharacterManagementHandler.Handle(LoginSession session, PacketReader packet) in E:\MapleServer2\MapleServer2\PacketHandlers\Login\CharacterManagementHandler.cs:line 36
   at MapleServer2.Network.PacketRouter`1.OnPacket(Object sender, PacketReader reader) in E:\MapleServer2\MapleServer2\Network\PacketRouter.cs:line 24
   at MapleServer2.Network.Session.ReadRecvPipe(PipeReader reader) in E:\MapleServer2\MapleServer2\Network\Session.cs:line 257
[06:48:07] [INF] LoginServer: Login client disconnected: LoginSession from 127.0.0.1:60684

**Comment by AngeloTadeucci** [comment]
Which job you were trying to create?

**Comment by AngeloTadeucci** [comment]
Can't reproduce. Character creation is fine, check if your Xml file is the correct one.
