### ISSUE TITLE
Some epic quests do not progress.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#761]
During some quests, such as The great winn stilton, there is a map in which the character changes, but the moment I proceed to this map, an error occurs on the server (however, the server does not shut down). And all functions except for shutting down whether the connection is lost. And when I reconnect, it enters the map that keeps having that problem and keeps getting errors. (There may be problems with some other quests, but I haven't found them yet)

(Sorry, I would like to write the code of the error, but I will update the error code later due to current computer repair
And, bad english)

* I have temporarily resolved the above issue. Access the SQL tool and change the map code to 2000001(Tria) in Database - Character - Map (?). And when I reconnected, I escaped (However, infinite fall T_T: In this case, find the Kerning City map code in the chat window and enter /m. Then find the quest code and enter /completequest)

**Comment by AngeloTadeucci** [comment]
What are the errors that happens when you enter the map? We need that information!

**Comment by Kustale** [comment]
(Forcibly restarting this quest.  /startquest 60100115 true
And, it's very long to write more details about this error.
Server version is September 13th)

1. Enter the door in Dark Wind HQ
2. This is where Lennon and Winn Stilton fall down.
3. The story begins (Lennon and Katvan's men fight), and Katvan appears at the end.
4. After the story. map changed. (Map name is Dark Wind HQ Passage)
5. Here, the character should be changed to Lennon, but it does not change, only my character. And I stop here and cannot proceed. (Disconnected from server)

An error occurred on the server and then hung up.
The content of that error:

[20:11:35] [ERR] FieldManager: System.Collections.Generic.KeyNotFoundException: The given key '10000' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at MapleServer2.Triggers.TriggerContext.SetSound(Int32 soundId, Boolean isEnabled) in D:\MapleServer2-master\MapleServer2\Triggers\FieldObjectTriggers.cs:line 182
   at Maple2.Trigger._52000138_qd._main.StateAct1_wave1.OnEnter()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-master\MapleServer2\Triggers\TriggerScript.cs:line 25
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__80_0() in D:\MapleServer2-master\MapleServer2\Managers\FieldManager.cs:line 1322

**Comment by Kustale** [comment]
> What are the errors that happens when you enter the map? We need that information!

(Forcibly restarting this quest.  /startquest 60100115 true
And, it's very long to write more details about this error.
Server version is September 13th)

1. Enter the door in Dark Wind HQ
2. This is where Lennon and Winn Stilton fall down.
3. The story begins (Lennon and Katvan's men fight), and Katvan appears at the end.
4. After the story. map changed. (Map name is Dark Wind HQ Passage)
5. Here, the character should be changed to Lennon, but it does not change, only my character. And I stop here and cannot proceed. (Disconnected from server)

An error occurred in the server (the server does not shut down).
The content of that error:

[20:11:35] [ERR] FieldManager: System.Collections.Generic.KeyNotFoundException: The given key '10000' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at MapleServer2.Triggers.TriggerContext.SetSound(Int32 soundId, Boolean isEnabled) in D:\MapleServer2-master\MapleServer2\Triggers\FieldObjectTriggers.cs:line 182
   at Maple2.Trigger._52000138_qd._main.StateAct1_wave1.OnEnter()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-master\MapleServer2\Triggers\TriggerScript.cs:line 25
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__80_0() in D:\MapleServer2-master\MapleServer2\Managers\FieldManager.cs:line 1322

* Re-upload

**Comment by biesu** [comment]
大哥国人否

**Comment by biesu** [comment]
国人+qq619960911
