### ISSUE TITLE
An error when the enemy uses a skill in some dungeons.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#774]
**Describe the bug**

As you move halfway through the dungeons of Cherry Blossom Hill, Lazy Stumpy breathes, creating a storm effect.
Then an error occurred on the server and the connection to the server was lost.

**To Reproduce**
Example:
1. Use X item...
2. Enter X map...
3. Error happens

-----------------

1. Move about 2/3 of the cherry blossom hill (coordinates unknown)
2. Lazy Stumpy inhales and exhales along the way.
3. Crash.

**Expected behavior**

Server disconnection, error

**Screenshots**

![20221005_014950_00](https://user-images.githubusercontent.com/113628110/193879980-22cee387-931e-4732-992d-02efbf0f376a.jpg)
![234987](https://user-images.githubusercontent.com/113628110/193880183-99d47e9b-4171-4fee-894f-1235be96c07f.jpg)

**Stack trace of the error**
Copy the error from the console of MapleServer2

[01:46:49] [ERR] FieldManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Types.RegionSkillHandler.HandleEffect(FieldManager field, SkillCast skillCast, IFieldActor target) in D:\MapleServer2-P1\MapleServer2\Types\RegionSkillHandler.cs:line 19
   at MapleServer2.Triggers.TriggerContext.SetSkill(Int32[] triggerIds, Boolean arg2) in D:\MapleServer2-P1\MapleServer2\Triggers\FieldObjectTriggers.cs:line 175
   at Maple2.Trigger._02000290_bf._wind.StateActivateSkill.Execute()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-P1\MapleServer2\Triggers\TriggerScript.cs:line 29
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__80_0() in D:\MapleServer2-P1\MapleServer2\Managers\FieldManager.cs:line 1347

**Latest commit id**
If you are using git, open the MapleServer 2 folder in the command prompt and do: `git log --oneline` and copy the first line

I not use git

**Comment by Kustale** [comment]
* The issue does not occur before Oct 1, 2022 version.

**Comment by mettaursp** [comment]
I'll look into it while I work on the next skills change. I think I see what is happening, I just need to verify.

**Comment by AngeloTadeucci** [comment]
- #782
Will somewhat fix this @mettaursp
