### ISSUE TITLE
Dungeon error on updated server

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#785]
**Describe the bug**

A dungeon that was completed on the previous version server had an error on the new version server.

**To Reproduce**
Example:
1. Use X item...
2. Enter X map...
3. Error happens

---------------------------------------------------------

1. Enter the Root of Darkness Dungeon.
2. Meet Lennon and proceed to the next stage
3. The moment when the obstacle blocking the entrance to the next floor is about to be removed...

**Expected behavior**

Connection lost, server error.

**Screenshots**

![20221018_233120_00](https://user-images.githubusercontent.com/113628110/196459826-713e769d-3186-4e11-ab9e-4b618fdb08e1.jpg)

**Stack trace of the error**
Copy the error from the console of MapleServer2

[23:19:45] [ERR] FieldManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Types.RegionSkillHandler.HandleEffect(FieldManager field, SkillCast skillCast, IFieldActor target) in D:\MapleServer2-P2\MapleServer2\Types\RegionSkillHandler.cs:line 19
   at MapleServer2.Triggers.TriggerContext.SetSkill(Int32[] triggerIds, Boolean arg2) in D:\MapleServer2-P2\MapleServer2\Triggers\FieldObjectTriggers.cs:line 175
   at Maple2.Trigger._52000076_qd._main.State진행08.Execute()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-P2\MapleServer2\Triggers\TriggerScript.cs:line 29
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__80_0() in D:\MapleServer2-P2\MapleServer2\Managers\FieldManager.cs:line 1347

**Latest commit id**
If you are using git, open the MapleServer 2 folder in the command prompt and do: `git log --oneline` and copy the first line

I not use git.

**Comment by Kustale** [comment]
Ah, confirmed that it was a skill problem... I will delete it.

**Comment by AngeloTadeucci** [comment]
Yeah this is the same error as before, it'll "fixed" with #782
