### ISSUE TITLE
Umm, an error occurred in some dungeons

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#789]
**Describe the bug**

An error in the effect that appears after catching the boss in some dungeons. (Illusory Pyramid)

**To Reproduce**

1. Enter the Illusory Pyramid.
2. A boss appears during the process.
3. Catch the boss.
4. After that, the sandstorm (?) effect appeared.

**Expected behavior**

The sandstorm passes and the map does not move and the server is disconnected.
Then, an error occurred on the server.

**Screenshots**

![34653647584](https://user-images.githubusercontent.com/113628110/197542216-8bf37528-f299-4ccf-803d-f0d03d3c041c.jpg)
And, video (file is too large to upload.)
https://drive.google.com/file/d/1NenZLYiU9bu-_q9SUuO0U2asYRt0BfqU/view?usp=sharing

**Stack trace of the error**

[22:43:49] [ERR] FieldManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Types.RegionSkillHandler.RegionHitTarget(FieldManager field, SkillCast skillCast, Int32& hitsRemaining, List`1 damages, IFieldActor target, Boolean damaging) in D:\MapleServer2-P1\MapleServer2\Types\RegionSkillHandler.cs:line 332
   at MapleServer2.Types.RegionSkillHandler.RegionHitPlayer(FieldManager field, SkillCast skillCast, Int32& hitsRemaining, List`1 damages) in D:\MapleServer2-P1\MapleServer2\Types\RegionSkillHandler.cs:line 261
   at MapleServer2.Types.RegionSkillHandler.HandleRegionSkill(FieldManager field, SkillCast skillCast) in D:\MapleServer2-P1\MapleServer2\Types\RegionSkillHandler.cs:line 212
   at MapleServer2.Types.RegionSkillHandler.HandleEffect(FieldManager field, SkillCast skillCast, IFieldActor target) in D:\MapleServer2-P1\MapleServer2\Types\RegionSkillHandler.cs:line 35
   at MapleServer2.Triggers.TriggerContext.SetSkill(Int32[] triggerIds, Boolean arg2) in D:\MapleServer2-P1\MapleServer2\Triggers\FieldObjectTriggers.cs:line 174
   at Maple2.Trigger._02010070_bf._main.StateStart5.Execute()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-P1\MapleServer2\Triggers\TriggerScript.cs:line 29
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__79_0() in D:\MapleServer2-P1\MapleServer2\Managers\FieldManager.cs:line 1320

**Latest commit id**

**Comment by Kustale** [comment]
Occurs in recent server versions.
Normal in the version before the skill fix.
