### ISSUE TITLE
Unknown column 'prestige_rewards_claimed' in 'field list'

### ISSUE THREAD

**Issue by Maplems** [AlanMorel/MapleServer2#793]
[2022-10-26 16:32:57] [Information] MapleServer2.Database.DatabaseManager: Found supported MySQL version.
[2022-10-26 16:32:57] [Information] MapleServer2.Database.DatabaseManager: Creating database...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding Shops...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding ShopItems...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding BeautyShops...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding BeautyShopItems...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding MeretMarket...
[2022-10-26 16:32:59] [Information] MapleServer2.Database.DatabaseManager: Seeding Mapleopoly...
[2022-10-26 16:33:00] [Information] MapleServer2.Database.DatabaseManager: Seeding Events...
[2022-10-26 16:33:00] [Information] MapleServer2.Database.DatabaseManager: Seeding CardReverseGame...
[2022-10-26 16:33:00] [Information] MapleServer2.Database.DatabaseManager: Seeding RouletteGameItems...
[2022-10-26 16:33:00] [Information] MapleServer2.Database.DatabaseManager: Seeding OXQuiz...
[2022-10-26 16:33:00] [Information] MapleServer2.Database.DatabaseManager: Database created.
[2022-10-26 16:33:00] [Fatal] MapleServer2.MapleServer: Exception Type: MySql.Data.MySqlClient.MySqlException
Message: Unknown column 'prestige_rewards_claimed' in 'field list'
Stack Trace:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443
   at SqlKata.Execution.QueryFactory.Statement(String sql, Object param, IDbTransaction transaction, Nullable`1 timeout)
   at MapleServer2.Database.DatabaseManager.RunQuery(String query) in D:\Maple2\MapleServer2\MapleServer2\Database\DatabaseManager.cs:line 123
   at MapleServer2.MapleServer.DailyReset() in D:\Maple2\MapleServer2\MapleServer2\MapleServer.cs:line 192
   at MapleServer2.MapleServer.Main() in D:\Maple2\MapleServer2\MapleServer2\MapleServer.cs:line 77
   at MapleServer2.MapleServer.<Main>()

**Comment by Kustale** [comment]
As a workaround, open a SQL tool (eg HeidiSQL) and add a prestige_rewards_claimed row to the account table.
![3753653](https://user-images.githubusercontent.com/113628110/198007481-217877d6-51d0-4ded-a09c-8e2cbac1a104.jpg)

* However, in this case, it is thought that previously used characters and information will not be usable. (Looking at the code, it looks like SQL has been partially modified)
I have to recreate and nurture my character... T_T
