### ISSUE TITLE
Problems with the tutorial map

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#795]
**Describe the bug**

Error after NPC appeared during the process.

**To Reproduce**

1. Create a Soul Binder character
2. Tutorial progress (When you start the tutorial, there should be a job video, but a black screen. But it will proceed if you wait)
3. Enemies appear and the player grabs them.
4. The moment Junta appears...

**Expected behavior**

stop as it is. Server down. Server error.

**Screenshots**

![20221027_144158_00](https://user-images.githubusercontent.com/113628110/198203607-ef96c346-23c8-4da9-bdb0-66f369b713fc.jpg)
![59375843](https://user-images.githubusercontent.com/113628110/198207906-79c7d4d9-e6fe-49e2-bd3e-9b039058cb4a.jpg)

And,  video.
https://drive.google.com/file/d/1KVoPOgxgxwakFF7sqKvvBpV9Quq0BUm5/view?usp=sharing

**Stack trace of the error**

[14:49:16] [ERR] FieldManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Types.RegionSkillHandler.RegionHitTarget(FieldManager field, SkillCast skillCast, Int32& hitsRemaining, List`1 damages, IFieldActor target, Boolean damaging) in D:\MapleServer2-New\MapleServer2\Types\RegionSkillHandler.cs:line 332
   at MapleServer2.Types.RegionSkillHandler.RegionHitPlayer(FieldManager field, SkillCast skillCast, Int32& hitsRemaining, List`1 damages) in D:\MapleServer2-New\MapleServer2\Types\RegionSkillHandler.cs:line 261
   at MapleServer2.Types.RegionSkillHandler.HandleRegionSkill(FieldManager field, SkillCast skillCast) in D:\MapleServer2-New\MapleServer2\Types\RegionSkillHandler.cs:line 212
   at MapleServer2.Types.RegionSkillHandler.HandleEffect(FieldManager field, SkillCast skillCast, IFieldActor target) in D:\MapleServer2-New\MapleServer2\Types\RegionSkillHandler.cs:line 35
   at MapleServer2.Triggers.TriggerContext.SetSkill(Int32[] triggerIds, Boolean arg2) in D:\MapleServer2-New\MapleServer2\Triggers\FieldObjectTriggers.cs:line 174
   at Maple2.Trigger._63000028_cs._battle01.StateJuntaApp04.OnExit()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-New\MapleServer2\Triggers\TriggerScript.cs:line 22
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__79_0() in D:\MapleServer2-New\MapleServer2\Managers\FieldManager.cs:line 1320

**Latest commit id**

**Comment by Kustale** [comment]
Fortunately, the new database on the old version server works just fine.
