### ISSUE TITLE
(I wonder if it's a bug...) When creating a wizard and starting a tutorial.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#809]
**Describe the bug**

A quest bug that occurs when I create a wizard character, start the tutorial, and near the end.
(Related to Alkimi Garden Quest)
= A bug that occurs when the quest item does not appear during the quest (also exists in the warrior character tutorial quest)

**To Reproduce**

1. Wizard character creation.
2. Start the tutorial quest.
3. Near the end... Enter the Tria library. (Normally, unless you're a Rune-blade or Wizard, you don't go through the Tria map. Wizard characters are considered to be visiting the library as a concept)
4. Talk to Anne.
5. Usually the quest below is a tutorial quest, but if you just press the space bar, the above quest will be accepted.
6. Accept the quest and move to Lith Harbor.
7. Quests usually appear on Marco, but this one appears on Loana in The Chest.
8. Accept the quest and enter Alkimi Island.
9. There is an NPC called Mani on that map. If you talk to him, the quest will proceed.
10. Then an item should be obtained but not obtained.
11. On the map ? If you go where there is a sign, there will be another NPC. His name is Antonius.
12. If you talk to it, a quest will appear, but if you press the space bar, it seems to proceed, but it just closes.
13. At this point, the moment you talk to this NPC again...
(However, even if you create another character for this quest, I think this quest will exist if you meet NPC anne in the Tria library later)

**Expected behavior**

Disconnected, server error.
And there's a quest that didn't come out before.

**Screenshots**

![6346357](https://user-images.githubusercontent.com/113628110/204021386-d9210130-e367-44ea-bb31-1b3ca818247b.jpg)
https://drive.google.com/file/d/1kOd0MBTDyllxouo1KOgARhpKOkf8yEpY/view?usp=sharing

**Stack trace of the error**

[00:44:14] [FTL] Session: Exception in recv PipeScheduler: MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry '60110050-1' for key 'quests.quests_un'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1062
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at SqlKata.Execution.QueryFactory.Get[T](Query query, IDbTransaction transaction, Nullable`1 timeout)
   at SqlKata.Execution.QueryExtensions.InsertGetId[T](Query query, Object data, IDbTransaction transaction, Nullable`1 timeout)
   at MapleServer2.Database.Classes.DatabaseQuest.Insert(QuestStatus questStatus) in D:\MapleServer2-P1\MapleServer2\Database\Classes\DatabaseQuest.cs:line 15
   at MapleServer2.Types.QuestStatus..ctor(Int64 characterId, QuestMetadata metadata, QuestState state, Int64 startTimestamp, Boolean accepted) in D:\MapleServer2-P1\MapleServer2\Types\QuestStatus.cs:line 61
   at MapleServer2.Types.QuestStatus..ctor(Int64 characterId, Int32 questId, QuestState state, Int64 startTimestamp, Boolean accepted) in D:\MapleServer2-P1\MapleServer2\Types\QuestStatus.cs:line 43
   at MapleServer2.PacketHandlers.Game.NpcTalkHandler.HandleNextQuest(GameSession session, PacketReader packet) in D:\MapleServer2-P1\MapleServer2\PacketHandlers\Game\NpcTalkHandler.cs:line 541
   at MapleServer2.PacketHandlers.Game.NpcTalkHandler.Handle(GameSession session, PacketReader packet) in D:\MapleServer2-P1\MapleServer2\PacketHandlers\Game\NpcTalkHandler.cs:line 54
   at MapleServer2.Network.PacketRouter`1.OnPacket(Object sender, PacketReader reader) in D:\MapleServer2-P1\MapleServer2\Network\PacketRouter.cs:line 23
   at MapleServer2.Network.Session.ReadRecvPipe(PipeReader reader) in D:\MapleServer2-P1\MapleServer2\Network\Session.cs:line 263

And,

[00:42:39] [INF] ScriptLoader: Script Npcs/11003878 does not exist.
[00:42:39] [WRN] NpcTalkHandler: Unhandled NPC 11003878 with multiple possible talk scripts

[00:44:56] [INF] ScriptLoader: Script Npcs/11003879 does not exist.
[00:44:56] [WRN] NpcTalkHandler: Unhandled NPC 11003879 with multiple possible talk scripts

**Latest commit id**

**Comment by Kustale** [comment]
A temporary workaround. Don't hit the space bar while doing quests.
...

**Comment by AngeloTadeucci** [comment]
It's a bug, but its not really directly related to wizards. It's related to #62 , somehow you managed have the quest in the database but the client didn't recognized it and tried to add the same quest again.
