### ISSUE TITLE
How to play DDS(Dance Dance Stop) [No bug report]

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#812]
![20221215_204429_00](https://user-images.githubusercontent.com/113628110/207852330-89846b3d-ee11-4788-bfca-774739604899.jpg)
![20221215_204558_02](https://user-images.githubusercontent.com/113628110/207852409-759635ee-446a-471f-a979-e879d121379f.jpg)
![20221215_204959_03](https://user-images.githubusercontent.com/113628110/207852450-744566c5-8619-4075-b4d1-805abc9fd2ab.jpg)
![20221215_205004_04](https://user-images.githubusercontent.com/113628110/207852486-da45d1e3-ec49-4a99-bc25-3186cda84ac0.jpg)

At first, entering this event map does not start.
At this time, move the character into this field to start.

1. Enter command /coord -971, 1190, 1651
2. Enjoy.

**Comment by Kustale** [comment]
This method can also be used with other event maps (however, the location is different for each event map).
However, in some event maps, if you fail or exit midway, you will not be able to escape.
In Spring Beach, it works automatically, but an error occurs at the end.
(Error in the result window after the event)

Below is the error that occurs when the result window pops up in Spring Beach :

[2022-12-15 21:38:35] [Error] MapleServer2.Managers.FieldManager: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at MapleServer2.Triggers.TriggerContext.SetEventUI(Byte typeId, String script, Int32 duration, String box) in D:\MapleServer2-First\MapleServer2\Triggers\UITriggers.cs:line 178
   at Maple2.Trigger._61000007_me._mainprocess_springbeach.State우승자CameraCinematic.OnEnter()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-First\MapleServer2\Triggers\TriggerScript.cs:line 25
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__91_0() in D:\MapleServer2-First\MapleServer2\Managers\FieldManager.cs:line 1489
