### ISSUE TITLE
Error when trying to move a portal on a specific map.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#819]
**Describe the bug**

A serious error occurred on the server when trying to enter and exit a specific map (dungeon).

**To Reproduce**

1. Enter the Waterbug Landing dungeon.
2. After proceeding, enter the Waterbug Park dungeon.
3. Also proceed and exit. -> Return to Waterbug Landing again without dungeon exiting.
4. Use the portal in the back.

**Expected behavior**

ka-boom
Unlike other errors, the server completely shuts down.

**Screenshots**

![20230106_155513_00](https://user-images.githubusercontent.com/113628110/210947138-86587040-47f0-4e97-90f7-3001f92e95a4.jpg)
![938740262](https://user-images.githubusercontent.com/113628110/210948028-1984a285-d44a-4a02-89d0-ef947441f9a7.jpg)

**Stack trace of the error**

Process terminated. Assertion failed.
Should never be null
   at MapleServer2.PacketHandlers.Game.MoveFieldHandler.HandleMove(GameSession session, PacketReader packet) in D:\MapleServer2-First\MapleServer2\PacketHandlers\Game\MoveFieldHandler.cs:line 85
   at MapleServer2.PacketHandlers.Game.MoveFieldHandler.Handle(GameSession session, PacketReader packet) in D:\MapleServer2-First\MapleServer2\PacketHandlers\Game\MoveFieldHandler.cs:line 36
   at MapleServer2.Network.PacketRouter`1.OnPacket(Object sender, PacketReader reader) in D:\MapleServer2-First\MapleServer2\Network\PacketRouter.cs:line 23
   at MapleServer2.Network.Session.ReadRecvPipe(PipeReader reader) in D:\MapleServer2-First\MapleServer2\Network\Session.cs:line 263
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at MapleServer2.Network.QueuedPipeScheduler.ProcessQueue() in D:\MapleServer2-First\MapleServer2\Network\QueuedPipeScheduler.cs:line 34
   at MapleServer2.Network.Session.StartInternal() in D:\MapleServer2-First\MapleServer2\Network\Session.cs:line 196
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

**Latest commit id**

**Comment by biesu** [comment]
Hello, what's the progress now?
