### ISSUE TITLE
Sudden error infinite multiplication...

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#821]
**Describe the bug**

The reason is unknown, but the error repeats infinitely from a certain point.

**To Reproduce**

I guess:

1. Error in adding skill. (Swift Blade) **
2. Error moving from Safehold in Kritias to Sky Fortress.

**Expected behavior**

The server doesn't disconnect, but the error persists and lags.
+ Swift Blade's icon blinks quickly. (It does not blink when the skill of Swift Blade is released. But the error continues)

**Screenshots**

![3653737352443](https://user-images.githubusercontent.com/113628110/212425641-3e08a297-1ad0-4fcf-8a6a-383008ee8ac4.jpg)
![20230114_065219_01](https://user-images.githubusercontent.com/113628110/212427277-6929244a-2c87-452c-994f-85369f643de7.jpg)

**Stack trace of the error**

[06:42:23] [ERR] FieldManager: Error in field logic loop System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MapleServer2.Types.Player.ProcessPassiveSkills() in D:\MapleServer2-First\MapleServer2\Types\Player.cs:line 1089
   at MapleServer2.Types.Player.<InitializeEffects>b__209_0() in D:\MapleServer2-First\MapleServer2\Types\Player.cs:line 866
   at MapleServer2.Types.TickingTaskScheduler.<>c__DisplayClass10_0.<QueueBufferedTask>b__0(Int64 currentTick, TriggerTask task) in D:\MapleServer2-First\MapleServer2\Types\FieldTaskScheduler\TickingTaskScheduler.cs:line 74
   at MapleServer2.Types.TickingTaskScheduler.Update(Int64 delta) in D:\MapleServer2-First\MapleServer2\Types\FieldTaskScheduler\TickingTaskScheduler.cs:line 160
   at MapleServer2.Managers.Actors.FieldActor`1.Update(Int64 delta) in D:\MapleServer2-First\MapleServer2\Managers\Actors\FieldActor.cs:line 332
   at MapleServer2.Managers.FieldManager.UpdateActors(Int64 delta) in D:\MapleServer2-First\MapleServer2\Managers\FieldManager.cs:line 1306
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 8F F9 D8 7B 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 49 52 A6 00 01 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 FF FF FF FF 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 99 52 A6 00 06 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 FF FF FF FF 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 9A 52 A6 00 06 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 FF FF FF FF 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 9B 52 A6 00 06 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 BB 3E FC 6B 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 AD 52 A6 00 0A 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 FF FF FF FF 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 C2 52 A6 00 0A 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 93 B4 B5 04 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 11 53 A6 00 05 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 3B 57 4B 7B 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 12 53 A6 00 05 00 01 00 00 00 01
[06:42:23] [DBG] Session: SEND (Buff - 0x0048): 02 42 42 0F 00 FF FF FF FF 42 42 0F 00 01 00 00 00 DA 15 45 00 DA 15 45 00 2F 53 A6 00 01 00 01 00 00 00 01

**Latest commit id**

**Comment by mettaursp** [comment]
Yeah that one appears with a couple of different skills on the current master build. I've got a fix for it in my current batch of changes, but I'm not sure when I'll be setting up a pull request for it yet. I think changing `.First(` to `.FirstOrDefault(` in `D:\MapleServer2-First\MapleServer2\Types\Player.cs:line 1089` should work as a temporary fix until then.

**Comment by mettaursp** [comment]
The fix for this just got pushed

**Comment by AngeloTadeucci** [comment]
- #823
