### ISSUE TITLE
It's been a while since I posted a bug(?) report.

### ISSUE THREAD

**Issue by Kustale** [AlanMorel/MapleServer2#822]
**Describe the bug**

Error when progressing in the Palace Undercroft dungeon.

**To Reproduce**

1. Enter the Palace Undercroft dungeon.
2. Early progress.

3. Boom.

(I wonder if the water drop effect behind is a problem. A water drop occurs behind this dungeon and it has a poison effect)

**Expected behavior**

server error. Connection lost.

**Screenshots**

![385732952](https://user-images.githubusercontent.com/113628110/216750836-c4220d53-ffb6-4025-9f07-d88e551e4644.jpg)
![20230204_143649_00](https://user-images.githubusercontent.com/113628110/216750843-96067001-0e0f-40ea-9b4c-c15ab776278a.jpg)

**Stack trace of the error**

[14:36:04] [ERR] FieldManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleServer2.Triggers.TriggerContext.SetSkill(Int32[] triggerIds, Boolean arg2) in D:\MapleServer2-P57\MapleServer2\Triggers\FieldObjectTriggers.cs:line 169
   at Maple2.Trigger._02000252_bf._start.StateSkill08.OnEnter()
   at MapleServer2.Triggers.TriggerScript.Next() in D:\MapleServer2-P57\MapleServer2\Triggers\TriggerScript.cs:line 25
   at MapleServer2.Managers.FieldManager.<StartTriggerTask>b__91_0() in D:\MapleServer2-P57\MapleServer2\Managers\FieldManager.cs:line 1487

**Latest commit id**

**Comment by darkvergus** [comment]
This is not exactly much of a bug and more of a feature missing as dungeons haven't exactly progress much in terms of feature complete
